-- MySQL Script generated by MySQL Workbench
-- Mon Mar  6 10:13:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido1` VARCHAR(45) NULL,
  `apellido2` VARCHAR(45) NULL,
  `correoElectronico` VARCHAR(45) NULL,
  `celular` VARCHAR(20) NULL,
  `direccion` VARCHAR(100) NULL,
  `antiguedadEmpleado` DATE NULL,
  `tipoDeSangreRH` VARCHAR(45) NULL,
  `tipoDeEmpleado` ENUM('COORDINADOR', 'REPARTIDOR', 'CONDUCTOR') NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido1` VARCHAR(45) NULL,
  `apellido2` VARCHAR(45) NULL,
  `correoElectronico` VARCHAR(45) NULL,
  `celular` VARCHAR(20) NULL,
  `direccion` VARCHAR(100) NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paquete` (
  `idPaquete` INT NOT NULL,
  `tipoDePaquete` ENUM('LIVIANO', 'MEDIANO', 'GRANDE') NOT NULL,
  `peso` FLOAT NOT NULL,
  `valorDeclarado` DOUBLE NOT NULL,
  PRIMARY KEY (`idPaquete`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Envio` (
  `numeroGuia` CHAR(10) NOT NULL,
  `Cliente_cedula` INT NOT NULL,
  `ciudadOrigen` VARCHAR(45) NOT NULL,
  `ciudadDestino` VARCHAR(45) NOT NULL,
  `direccionDestino` VARCHAR(100) NOT NULL,
  `nombrePersonaQueRecibe` VARCHAR(45) NOT NULL,
  `celularPersonaQueRecibe` VARCHAR(20) NOT NULL,
  `horaEntrega` DATETIME NULL,
  `estadoEnvio` VARCHAR(45) NOT NULL DEFAULT 'RECIBIDO',
  `valorEnvio` DOUBLE NULL,
  `idPaquete` INT NOT NULL,
  PRIMARY KEY (`numeroGuia`, `Cliente_cedula`, `idPaquete`),
  INDEX `fk_Envio_Paquete_idx` (`idPaquete` ASC) VISIBLE,
  INDEX `fk_Envio_Cliente1_idx` (`Cliente_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Envio_Paquete`
    FOREIGN KEY (`idPaquete`)
    REFERENCES `mydb`.`Paquete` (`idPaquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Envio_Cliente1`
    FOREIGN KEY (`Cliente_cedula`)
    REFERENCES `mydb`.`Cliente` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
